name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install pipenv
        run: pipx install pipenv
      - name: Install dependencies
        run: pipenv install --deploy --dev
      - name: Lint files
        run: make lint
      - name: Check formatting of files
        run: make format-check
